[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]] 
  name = "Scripts"
  pageRef = "scripts"
  weight = 30

[[main]]
  name = "Commands"
  pageRef = "commands"
  weight = 40

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 50

[[footer]]
   name = "Posts"
   pageRef = "posts"
   weight = 10

[[footer]]
   name = "Commands"
   pageRef = "commands"
   weight = 20

[[footer]] 
  name = "Scripts"
  pageRef = "scripts"
  weight = 30


 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 40

